name: Docker Image CI

on:
  workflow_dispatch
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ${{github.workspace}}/apis/poi/web --file ${{github.workspace}}/apis/poi/web/Dockerfile --tag api-poi:$(date +%s)
