# This is a basic workflow to help you get started with Actions

name: POI-BUILD-PUSH

on:
  workflow_dispatch
  
env:
  ACRNAME: "openhackck258x60acr"
  IMAGE_NAME_POI: "devopsoh/api-poi"
  BASEIMAGETAG_POI: "0.1.0"
  

jobs:

  Build_Image:
    runs-on: ubuntu-20.04

    steps:

    - name: Recuperation du repos 
      uses: actions/checkout@v2
        
    - name: Docker Build POI
      run: |
        cd apis/poi/web && docker build . -t ${{ env.ACRNAME }}.azurecr.io/${{ env.IMAGE_NAME_POI }}:${{ env.BASEIMAGETAG_POI }}      
    
    - name: Login ACR for push
      uses: Azure/login@v1
      with:        
        creds: ${{secrets.AZURE_CREDENTIALS}}
        
    - name: Log ACR
      run: |
        az acr login --name ${{ env.ACRNAME }}
        
    - name: Push to ACR
      run: |
        docker push ${{ env.ACRNAME }}.azurecr.io/${{ env.IMAGE_NAME_POI }}:${{ env.BASEIMAGETAG_POI }}
       
    
        
        
        




