name: .NET

on:
  push:
    paths:
      - 'apis/poi/**'
    branches: [ main ]
  pull_request:
    paths:
      - 'apis/poi/**'
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./apis/poi/
    defaults:
      run:
        working-directory: ${{env.working-directory}}
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore ./apis/poi/web/poi.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal ./apis/poi/tests/UnitTests/UtilityTests.cs
