name: .NET

on:
  push:
    paths:
      - 'apis/poi/**'
    branches: [ main ]
  pull_request:
    paths:
      - 'apis/poi/**'
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore ${{github.workspace}}/apis/poi
    - name: Build
      run: dotnet build --no-restore ${{github.workspace}}/apis/poi/web
    - name: Test
      run: dotnet test --no-build --verbosity normal ${{github.workspace}}/apis/poi/tests/UnitTests
