# This is a basic workflow to help you get started with Actions

name: Test-Buil-Push

on:
  workflow_dispatch
  
env:
  ACR_NAME: openhackck258x60acr
  IMAGE_NAME: changeme
  

jobs:

  Build_Image:
    runs-on: ubuntu-20.04

    steps:

    - name: Recuperation du repos 
      uses: actions/checkout@v2      

    - name: Connexion à Azure Container Registry
      uses: docker/login-action@v1.10.0
      with:
        registry: ${{ env.ACR_NAME }}.azurecr.io
        username: ${{ env.ACR_NAME }}
        password: "${{ secrets.ACR_KEY }}"
        
    - name: Extraire les métadonnées docker
      id: meta
      uses: docker/metadata-action@v3.6.0
      with:
        images: ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }} 
        tags: |
         type=semver,pattern={{version}},value=${{ env.IMAGE_VERSION }}



