# This is a basic workflow to help you get started with Actions

name: TRIPS-BUILD-PUSH

on:
  push:
    paths:
      - 'apis/trips/**'
      - '.github/workflows/TRIPS-BUILD-PUSH.yml'
    branches: [ main ]
  pull_request:
    paths:
      - 'apis/trips/**'
      - '.github/workflows/TRIPS-BUILD-PUSH.yml'
    branches: [ main ]
  
env:
  CONTAINER_REGISTRY: openhackck258x60acr.azurecr.io
  ACRNAME: "openhackck258x60acr"
  IMAGE_NAME_TRIPS: "devopsoh/api-trips"
  BASEIMAGETAG_TRIPS: ${{ github.sha }}
  AZURE_WEBAPP_NAME: "openhackck258x60trips"


jobs:

  Build_Image:
    runs-on: ubuntu-20.04

    steps:

    - name: Recuperation du repos 
      uses: actions/checkout@v2
        
#    - name: Docker Build TRIPS
#      run: |
#        cd apis/trips && docker build . -t ${{ env.ACRNAME }}.azurecr.io/${{ env.IMAGE_NAME_TRIPS }}:${{ env.BASEIMAGETAG_TRIPS }}      
    
    - name: Login ACR for push
      uses: Azure/login@v1
      with:        
        creds: ${{secrets.AZURE_CREDENTIALS}}
        
    - name: Log ACR
      run: |
        az acr login --name ${{ env.ACRNAME }}
        
#    - name: Push to ACR
#      run: |
#        docker push ${{ env.ACRNAME }}.azurecr.io/${{ env.IMAGE_NAME_TRIPS }}:${{ env.BASEIMAGETAG_TRIPS }}

    - name: Start the stage
      run: |
        az webapp start -g openhackck258x60rg -n ${{ env.AZURE_WEBAPP_NAME }} --slot staging
    
#    - name: 'Deploy to Azure Web App for Container'
#      uses: azure/webapps-deploy@v2
#      with: 
#        app-name: ${{ env.AZURE_WEBAPP_NAME }} 
#        images: ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME_TRIPS }}:${{ env.BASEIMAGETAG_TRIPS }}
        
    - name: 'Swap'
      run: |
        sleep 15s
        testStage=`curl -sb -i https://openhackck258x60trips-staging.azurewebsites.net/api/healthcheck/trips | grep -q Healthy && echo "success" || echo 'failed'`
        echo 'testStage' $testStage
        [ $testStage == 'success' ] && az webapp deployment slot swap -g openhackck258x60rg -n ${{ env.AZURE_WEBAPP_NAME }} --slot staging --target-slot production
        testProd=`curl -sb -i https://openhackck258x60trips.azurewebsites.net/api/healthcheck/trips | grep -q Healthy && echo "success" || echo 'failed'`
        echo 'testProd' $testProd
        [ $testProd != 'success' ] && az webapp deployment slot swap -g openhackck258x60rg -n ${{ env.AZURE_WEBAPP_NAME }} --slot production --target-slot staging || echo "Successful"
        
    - name: Stop the stage
      run: |
        az webapp stop -g openhackck258x60rg -n ${{ env.AZURE_WEBAPP_NAME }} --slot staging
