# This is a basic workflow to help you get started with Actions

name: userprofile
on:
  push:
    paths:
      - 'apis/userprofile/**'
      - '.github/workflows/userprofile.yml'
    branches: [ main ]
  pull_request:
    paths:
      - 'apis/userprofile/**'
      - '.github/workflows/userprofile.yml'
    branches: [ main ]
  
env:
  ACRNAME: "openhackck258x60acr"
  IMAGE_NAME_USERPROFILE: "devopsoh/api-userprofile"
  BASEIMAGETAG_USERPROFILE: ${{ github.sha }}
  AZURE_WEBAPP_NAME: "openhackck258x60userprofile"
  CONTAINER_REGISTRY: openhackck258x60acr.azurecr.io


jobs:

  Build_Image:
    runs-on: ubuntu-20.04

    steps:

    - name: Recuperation du repos 
      uses: actions/checkout@v2
        
    - name: Docker Build USERPROFILE
      run: |
        cd apis/userprofile && docker build . -t ${{ env.ACRNAME }}.azurecr.io/${{ env.IMAGE_NAME_USERPROFILE }}:${{ env.BASEIMAGETAG_USERPROFILE }}      
    
    - name: Login ACR for push
      uses: Azure/login@v1
      with:        
        creds: ${{secrets.AZURE_CREDENTIALS}}
        
    - name: Log ACR
      run: |
        az acr login --name ${{ env.ACRNAME }}
        
    - name: Push to ACR
      run: |
        docker push ${{ env.ACRNAME }}.azurecr.io/${{ env.IMAGE_NAME_USERPROFILE }}:${{ env.BASEIMAGETAG_USERPROFILE }}
    
    - name: 'Deploy to Azure Web App for Container'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }} 
        images: ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME_USERPROFILE }}:${{ env.BASEIMAGETAG_USERPROFILE }}

       
    
        
        
        




