# This is a basic workflow to help you get started with Actions

name: userprofile

on:
  workflow_dispatch
  
env:
  ACRNAME: "openhackck258x60acr"
  IMAGE_NAME_POI: "devopsoh/api-userprofile"
  BASEIMAGETAG_POI: ${{ github.sha }}
  AZURE_WEBAPP_NAME: "openhackck258x60userprofile"


jobs:

  Build_Image:
    runs-on: ubuntu-20.04

    steps:

    - name: Recuperation du repos 
      uses: actions/checkout@v2
        
    - name: Docker Build USERPROFILE
      run: |
        cd apis/userprofile && docker build . -t ${{ env.ACRNAME }}.azurecr.io/${{ env.IMAGE_NAME_POI }}:${{ env.BASEIMAGETAG_POI }}      
    
    - name: Login ACR for push
      uses: Azure/login@v1
      with:        
        creds: ${{secrets.AZURE_CREDENTIALS}}
        
    - name: Log ACR
      run: |
        az acr login --name ${{ env.ACRNAME }}
        
    - name: Push to ACR
      run: |
        docker push ${{ env.ACRNAME }}.azurecr.io/${{ env.IMAGE_NAME_POI }}:${{ env.BASEIMAGETAG_POI }}
    
    - name: 'Deploy to Azure Web App for Container'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }} 
        images: ${{ env.ACRNAME }}/${{ env.IMAGE_NAME_POI }}:${{ env.BASEIMAGETAG_POI }}

       
    
        
        
        




